Update development branch with our own conditional formatter plugin
nus-mtp/lecture-note-2.0 pull request #196
Opened 2017-02-26 15:59 UTC by chuajiaxuan

Our own conditional formatter plugin!

# Features:
* Hiding document info on your commands!
* Hide different part of your documents for different versions! (e.g. Hide answers in student's copy, but show them in TA/Prof/Lecture's version) However, do note that this can only be _**fully functional**_ in later stages. Right now it is only tested with a pseudo document filename. This reflects that if document version/name is attainable, in the latter stages of development, this plugin will work.

# Usage:
* **Inline usage:** Start off the inline text/info you would like to hide with `=>hide` and end the line with `<=` _(Note: this syntax can be changed if the you guys find it not acceptable!)_
* **Block usage:** Start off with `==>hide` (note the extra `=`), _**AND**_ on a new paragraph type your text/info that you want to hide. Again, on a new paragraph, end off with `<==`.
    _**Example:**_
    ```
    // This is for Block usage.
    ==>hide
    This is where you type
    the chunk of info/text to
    hide, then end off with
   <==
    ```
    _**Special Use Case:**_
     ```
    // This is to test a special use case for Block hiding. The conditional hiding for
    // different versions of a document. First start off with your version/file name,
    // use this exact naming convention for now.
    fileName:*Input your doc/version name here*

    ==>hide:*Input doc/version name here as well*
    This is where you type
    the chunk of info/text to
    hide, then end off with
   <==

    ==>hide:*Input a different name here*
    Test test test
   <==
    ```

P.S.: You can even hide code blocks etc!

2017-02-26 17:18 UTC, amoshydra requested changes
Great job with the conditional formatter.

For now, I will have to reject this pull request, as there is currently a bug in the code that cause the app to stuck in a infinite loop. See [comment](https://github.com/nus-mtp/lecture-note-2.0/pull/196/files#diff-bfcd271c98652c4a2e5b8f0192a354d7R163).

Do read other comments too. 
Thanks.

2017-02-26 17:18 UTC, amoshydra commented on sashimi-webapp/src/logic/documentPackager/conditionalProcessor.js
> +  let mem;
Eslint is warning: `prefer-const`

If the variables here in this function may get reassigned in the future,  
consider suppressing the warning by adding `/* eslint prefer-const: 0 */` in the function.

2017-02-26 17:18 UTC, amoshydra commented on sashimi-webapp/src/logic/documentPackager/conditionalProcessor.js
> +      ) {
It is possible for this code to stuck in an infinity loop.

case: When user are in progress of typing out the condition without a `<==` tag at the back
```markdown
==>hide:
```

2017-02-26 17:18 UTC, amoshydra commented on sashimi-webapp/src/logic/documentPackager/conditionalProcessor.js
> +    for (;;) {
Extra care is needed when using a infinity loop. Make sure that the code can always get out of the loop in all condition.

2017-02-26 17:18 UTC, amoshydra commented on sashimi-webapp/src/logic/documentPackager/conditionalProcessor.js
> +    for (;;) {
Extra care is needed when using a infinity loop. Make sure that the code can always get out of the loop in all condition. [same for below]

2017-02-26 17:18 UTC, amoshydra commented on sashimi-webapp/src/logic/documentPackager/conditionalProcessor.js
> +  let mem;
It will be good to document/explain the variables listed here

2017-02-26 17:18 UTC, amoshydra commented on sashimi-webapp/src/logic/documentPackager/conditionalProcessor.js
> +/*
Consider using jsdoc documentation format for function.
http://usejsdoc.org/about-getting-started.html

VSCode is able to display jsdoc documentation when other developer hover over the functions

2017-02-26 19:22 UTC, chuajiaxuan commented on sashimi-webapp/src/logic/documentPackager/conditionalProcessor.js
> +      ) {
Resolved! Was careless, didn't put a check is nextLine exceeded endLine!

2017-02-26 19:25 UTC, chuajiaxuan commented on sashimi-webapp/src/logic/documentPackager/conditionalProcessor.js
> +    for (;;) {
The statement `if(nextLine >= endLine)` should take care to get out of the loop when endLine limit reached! It just the below case that I carelessly left out that check! :)

2017-02-26 19:40 UTC, chuajiaxuan commented on sashimi-webapp/src/logic/documentPackager/conditionalProcessor.js
> +  let mem;
Noted! Added descriptions and removed some redundant variables!

2017-02-26 21:10 UTC, amoshydra commented
In this commit,  
the code block will only hide when there is a space immediately after `==>hide`.  
Is this the intended behaviour?

```
==>hide 
this hide the block
<==
```

```
==>hide
this does not
<==
```

2017-02-28 05:02 UTC, chuajiaxuan commented
```
==>hide 
this hide the block
<==
```

```
==>hide
this does not
<==
```
This bug has been resolved in latest push! :) Thanks!

2017-02-28 15:30 UTC, amoshydra approved these changes

2017-02-28 20:29 UTC, merged