Ui/fix for ios
nus-mtp/lecture-note-2.0 pull request #386
Opened 2017-04-13 12:54 UTC by jiayingy

Fixed double click compatibility issues on iOS browser

2017-04-13 21:46 UTC, amoshydra requested changes

2017-04-13 21:46 UTC, amoshydra commented on sashimi-webapp/src/components/file-manager/File.vue
> +        this.isClickInProgress = false;
`this.isClickInProgress` is not the same with `this.onClickDetails.isClickInProgress`.
Therefore, `this.onClickDetails.isClickInProgress` is never set to false.

This result in second tapping to always be executed as a double click event.

2017-04-13 21:46 UTC, amoshydra commented on sashimi-webapp/src/components/file-manager/File.vue
> +      if (this.onClickDetails.isClickInProgress && event.x === this.onClickDetails.x && event.y === this.onClickDetails.y) {
`event.x === this.onClickDetails.x && event.y === this.onClickDetails.y` require the subsequent click to be in the exact same location.

This is very difficult for touch device as the finger is not likely to hit the exact coordinate.

You may either implement a threshold area or remove this check.

Threshold area e.g.
```javascript
dblClickCheck(event) {
  const threshold = 20;
  return (this.onClickDetails.isClickInProgress &&
          ((Math.abs(event.x - this.onClickDetails.x) < threshold) &&
            (Math.abs(event.y - this.onClickDetails.y) < threshold)
          ));
},
onClick(event) {
  if (this.dblClickCheck(event)) {
    this.openFile();
    this.clearIsClick();
    clearTimeout(this.clearIsClick);
  } else {
    this.onClickDetails.x = event.x;
    this.onClickDetails.y = event.y;
    this.onClickDetails.isClickInProgress = true;
    setTimeout(this.clearIsClick, 1000);
  }
},
```

I chose a threshold of 20 based on a quick experiment I conducted with my 5.5 inches screen Android phone.
Result showing data for 138 touches.

20px is equivalent to:

|Device|Screen Size (inches) |Actual (mm)|
---|---|---
Oneplus 3| 5.5 | 4.50
iPhone 5 | 5 | 3.47
Nexus 6P | 5.7 | 3.46
Nexus 5X | 5.2 | 3.16

![](http://i.imgur.com/MWqDo6v.png) 

<img src="http://i.imgur.com/23M57tP.png" width="360">

2017-04-14 06:13 UTC, jiayingy commented on sashimi-webapp/src/components/file-manager/File.vue
> +        this.isClickInProgress = false;
Have replaced it with threshold instead of checking for exact coordinates

2017-04-14 09:46 UTC, amoshydra approved these changes
This should work. 👍

2017-04-14 09:46 UTC, merged